reformat yaml

diff --git a/.github/workflows/lint-and-unit-tests.yml b/.github/workflows/lint-and-unit-tests.yml
--- a/.github/workflows/lint-and-unit-tests.yml
+++ b/.github/workflows/lint-and-unit-tests.yml
@@ -1,6 +1,6 @@
 name: Lint and Unit Tests
 
-on:
+'on':
   pull_request:
     branches:
       - dev
@@ -9,43 +9,35 @@ on:
     branches:
       - dev
       - main
-
 jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [20.x]
+        node-version:
+          - 20.x
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
-        
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: 'Use Node.js ${{ matrix.node-version }}'
         uses: actions/setup-node@v3
         with:
-          node-version: ${{ matrix.node-version }}
-          cache: 'npm'
-
+          node-version: '${{ matrix.node-version }}'
+          cache: npm
       - name: Install dependencies
         run: npm ci
-
       - name: Check for linting errors
-        run: npm run lint > lint-results.txt 2>&1 || echo "Linting failed" >> lint-results.txt
-
+        run: >-
+          npm run lint > lint-results.txt 2>&1 || echo "Linting failed" >>
+          lint-results.txt
       - name: Run tests
-        run: npm run testCoverage > test-results.txt 2>&1 || echo "Testing failed" >> test-results.txt
-
-      # - name: Set failure comment if failed for prs
-      #   if: ${{ failure() && github.event_name == 'pull_request' }}
-      #   run: echo "comment=Linting or unit tests failed" >> $GITHUB_ENV
-
-      # - name: Set success comment
-      #   run: echo "comment=Linting and unit tests succeeded" >> $GITHUB_ENV
-
+        run: >-
+          npm run testCoverage > test-results.txt 2>&1 || echo "Testing failed"
+          >> test-results.txt
       - name: Comment on PR
         if: always()
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
         run: |
           comment_body=""
 
@@ -69,4 +61,3 @@ jobs:
               -d "{\"body\": $comment_body}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
           fi
-
