write lint errors to comment

diff --git a/.github/workflows/lint-and-unit-tests.yml b/.github/workflows/lint-and-unit-tests.yml
--- a/.github/workflows/lint-and-unit-tests.yml
+++ b/.github/workflows/lint-and-unit-tests.yml
@@ -30,27 +30,38 @@ jobs:
         run: npm ci
 
       - name: Check for linting errors
-        run: npm run lint
+        run: npm run lint > lint-errors.txt || echo "Lint errors detected."
+
+      - name: Fail if lint errors are found
+        run: |
+          if [ -s lint-errors.txt ]; then
+            echo "Linting failed, errors are present."
+            exit 1
+          fi
 
       - name: Run tests
         run: npm run testCoverage
 
-      - name: Set failure comment if failed for prs
+      - name: Set failure comment if failed for PRs
         if: ${{ failure() && github.event_name == 'pull_request' }}
         run: echo "comment=Linting or unit tests failed" >> $GITHUB_ENV
 
       - name: Set success comment
+        if: ${{ success() }}
         run: echo "comment=Linting and unit tests succeeded" >> $GITHUB_ENV
 
-      - name: Comment on PR
-        if: always()
+      - name: Comment on PR with lint errors
+        if: always() && github.event_name == 'pull_request'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
-            echo "${{ env.comment }}"
-            curl -X POST \
-              -H "Authorization: Bearer $GITHUB_TOKEN" \
-              -d '{"body": "${{ env.comment }}"}' \
-              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
+          lint_errors=$(<lint-errors.txt)
+          if [ -n "$lint_errors" ]; then
+            comment_body="Linting errors found:\n\`\`\`\n$lint_errors\n\`\`\`"
+          else
+            comment_body="${{ env.comment }}"
           fi
+          curl -X POST \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -d "{\"body\": \"$comment_body\"}" \
+            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
